build: 
	go build

test: build
	cat test_input | ./19

test2: build
	cat test_input2 | ./19

run: build
	cat input | ./19

test_part2: build
	cat test_input_part2 | ./19 2

test2_part2: build
	cat test_input2_part2 | ./19 2

run_part2: build
	cat input | ./19 2
